export const menu = [
    {name: 'cantina tacos', price: 12, heat: 4, category: 'entrees', url: 'https://www.wellplated.com/wp-content/uploads/2020/05/Best-Tempeh-Tacos-Recipe-500x375.jpg', description:''},
    {name: 'stuffed burrito', price: 10, heat: 3, category: 'entrees', url: 'https://plantbasedandbroke.com/wp-content/uploads/2019/09/LRM_EXPORT_273713993199539_20190916_110156774-02.jpeg', description:''},
    {name: 'enchilada casserole', price: 10, heat: 3, category: 'entrees', url: 'https://food-fanatic-res.cloudinary.com/iu/s--xBitRK_G--/c_thumb,f_auto,g_auto,h_1200,q_auto,w_1200/v1559970975/vegetarian-enchilada-casserole-photo', description:''},
    {name: 'stuffed peppers', price: 12, heat: 3, category: 'entrees', url: 'https://happyhealthymama.com/wp-content/uploads/2016/09/CrockpotStuffedPeppers-8.jpg', description:''},
    {name: 'cantina bowl', price: 12, heat: 3, category: 'entrees', url: 'https://www.budgetbytes.com/wp-content/uploads/2019/04/Tempeh-Burrito-Bowls-V.jpg', description:''},
    {name: 'taco soup', price: 7, heat: 4, category: 'sides', url: 'https://theveglife.com/wp-content/uploads/2015/10/Tortilla-Soup.jpg', description:''},
    {name: 'house salad', price: 7, heat: 4, category: 'sides', url: 'https://simple-veganista.com/wp-content/uploads/2020/03/classic-house-salad.jpg', description:''},
    {name: 'spicy black beans', price: 7, heat: 4, category: 'sides', url: 'https://www.kindearth.net/wp-content/uploads/2017/10/Spicy-Beans_a4.jpg', description:''},
    {name: 'verde rice', price: 7, heat: 4, category: 'sides', url: 'https://houseofyumm.com/wp-content/uploads/2020/01/Mexican-Green-Rice-Arroz-Verde-7-680x520.jpg', description:''},
    {name: 'chips and salsa', price: 4, heat: 3, category: 'sides', url: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/12/9/0/FNK_Salsa-and-Chips_s4x3.jpg.rend.hgtvcom.616.462.suffix/1387411410179.jpeg', description:''},
    {name: 'skillet potatoes', price: 6, heat: 1, category: 'sides', url: 'https://www.bitesofberi.com/wp-content/uploads/2021/04/batata-harra-spicy-potatoes-1-500x500.jpg', description:''},
    {name: 'tempeh tacos', price: 8.99, heat: 3, category: 'entrees', url: 'https://mindfulavocado.com/wp-content/uploads/2021/05/tempeh-tacos_008-1100x1100.jpg', description:''},
    {name: 'loaded nachos', price: 10, heat: 4, category: 'appetizers', url: 'http://cdn.shopify.com/s/files/1/3002/1936/articles/vegan-nachos_1200x630.jpg?v=1614372751', description:''},
    {name: 'finger tacos', price: 12, heat: 3, category: 'appetizers', url: 'https://i0.wp.com/www.eatfigsnotpigs.com/wp-content/uploads/2020/04/Loaded-Vegan-Tiny-Tacos-8916.jpg?resize=1600%2C2400', description:''},
    {name: 'traditional guac', price: 7, heat: 2, category: 'appetizers', url: 'https://www.simplyrecipes.com/thmb/a4k8j7YDx2cJUdupcq9ja4NMbiM=/2000x1333/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2018__07__Guacamole-LEAD-2-924dbc47ba1e4ecd8e497bcd687cac4a.jpg', description:''},
    {name: 'tortilla soup', price: 7, heat: 3, category: 'appetizers', url: 'https://veganhuggs.com/wp-content/uploads/2021/03/vegan-tortilla-soup-square-crop.jpg', description:''},
    {name: 'churros', price: 5, heat: 0, category: 'desserts', url: 'https://www.recipetineats.com/wp-content/uploads/2016/08/Churros_9-SQ.jpg', description:''},
    {name: 'cantina cookie', price: 3, heat: 0, category: 'desserts', url: 'https://leitesculinaria.com/wp-content/uploads/fly-images/231496/david-leite-chocolate-chip-cookies-1-1200x900-c.jpg', description:''},
]